import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,ts}"],
  plugins: [daisyui],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Roboto", "Arial", "sans-serif"],
      },
      fontSize: {
        headline: "3.5rem",
        title: "2rem",
        body: "1rem",
        label: "0.875rem",
      },
    },
  },
  daisyui: {
    themes: [
      {
        light: {
          primary: "#6750A4",
          "primary-content": "#FFFFFF",
          secondary: "#625B71",
          "secondary-content": "#FFFFFF",
          accent: "#7952B3",
          "accent-content": "#FFFFFF",
          neutral: "#F1E0FF",
          "neutral-content": "#211A30",
          "base-100": "#FFFFFF",
          "base-200": "#EEE8F0",
          "base-300": "#E6E0E9",
          "base-content": "#1D1B20",
          info: "#2962FF",
          "info-content": "#FFFFFF",
          success: "#4CAF50",
          "success-content": "#FFFFFF",
          warning: "#FFC107",
          "warning-content": "#000000",
          error: "#B00020",
          "error-content": "#FFFFFF",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.3s",
          "--animation-input": "0.25s",
          "--btn-text-case": "capitalize",
          "--btn-focus-scale": "0.98",
          "--border-btn": "2px",
          "--tab-border": "2px",
          "--tab-radius": "0.5rem",
        },
        dark: {
          primary: "#D0BCFF",
          "primary-content": "#21005D",
          secondary: "#CCC2DC",
          "secondary-content": "#332D41",
          accent: "#EFB8C8",
          "accent-content": "#492532",
          neutral: "#141218",
          "neutral-content": "#FFFFFF",
          "base-100": "#1E1B20",
          "base-200": "#282529",
          "base-300": "#322F34",
          "base-content": "#E6E1E5",
          info: "#64B5F6",
          "info-content": "#1E1B20",
          success: "#66BB6A",
          "success-content": "#1E1B20",
          warning: "#FFD54F",
          "warning-content": "#1E1B20",
          error: "#EF5350",
          "error-content": "#1E1B20",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.3s",
          "--animation-input": "0.25s",
          "--btn-text-case": "capitalize",
          "--btn-focus-scale": "0.98",
          "--border-btn": "2px",
          "--tab-border": "2px",
          "--tab-radius": "0.5rem",
        },
      },
    ],
  },
};
