import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,ts}"],
  plugins: [daisyui],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Roboto", "Arial", "sans-serif"],
      },
      fontSize: {
        headline: "3.5rem",
        title: "2rem",
        body: "1rem",
        label: "0.875rem",
      },
    },
  },
  daisyui: {
    themes: [
      {
        light: {
          primary: "#6750A4",
          "primary-content": "#FFFFFF",
          secondary: "#625B71",
          "secondary-content": "#FFFFFF",
          accent: "#7D5260",
          "accent-content": "#FFFFFF",
          neutral: "#FEF7FF",
          "neutral-content": "#1D1B20",
          "base-100": "#FFFFFF",
          "base-200": "#F3EDF7",
          "base-300": "#E7E0EC",
          "base-content": "#49454F",
          info: "#2962FF",
          "info-content": "#FFFFFF",
          success: "#4CAF50",
          "success-content": "#FFFFFF",
          warning: "#FFC107",
          "warning-content": "#000000",
          error: "#B3261E",
          "error-content": "#FFFFFF",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.3s",
          "--animation-input": "0.25s",
          "--btn-text-case": "capitalize",
          "--btn-focus-scale": "0.98",
          "--border-btn": "2px",
          "--tab-border": "2px",
          "--tab-radius": "0.5rem",
        },
        dark: {
          primary: "#D0BCFF",
          "primary-content": "#381E72",
          secondary: "#CCC2DC",
          "secondary-content": "#332D41",
          accent: "#EFB8C8",
          "accent-content": "#492532",
          neutral: "#141218",
          "neutral-content": "#E6E0E9",
          "base-100": "#0F0D13",
          "base-200": "#211F26",
          "base-300": "#49454F",
          "base-content": "#CAC4D0",
          info: "#90CAF9",
          "info-content": "#121212",
          success: "#81C784",
          "success-content": "#121212",
          warning: "#FFCC80",
          "warning-content": "#121212",
          error: "#F2B8B5",
          "error-content": "#601410",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.5rem",
          "--animation-btn": "0.3s",
          "--animation-input": "0.25s",
          "--btn-text-case": "capitalize",
          "--btn-focus-scale": "0.98",
          "--border-btn": "2px",
          "--tab-border": "2px",
          "--tab-radius": "0.5rem",
        },
      },
    ],
  },
};
