import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,ts}"],
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#6750A4",
          "primary-content": "#FFFFFF",
          secondary: "#625B71",
          "secondary-content": "#FFFFFF",
          accent: "#7952B3",
          "accent-content": "#FFFFFF",
          neutral: "#F1E0FF",
          "neutral-content": "#211A30",
          "base-100": "#FFFFFF",
          "base-200": "#EEE8F0",
          "base-300": "#E6E0E9",
          "base-content": "#1D1B20",
          info: "#2962FF",
          success: "#4CAF50",
          warning: "#FFC107",
          error: "#B00020",
          "--rounded-box": "0.75rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
        dark: {
          primary: "#D0BCFF",
          "primary-content": "#21005D",
          secondary: "#CCC2DC",
          "secondary-content": "#332D41",
          accent: "#EFB8C8",
          "accent-content": "#492532",
          neutral: "#141218",
          "neutral-content": "#E6E1E5",
          "base-100": "#1E1B20",
          "base-200": "#282529",
          "base-300": "#322F34",
          "base-content": "#E6E1E5",
          info: "#64B5F6",
          success: "#66BB6A",
          warning: "#FFD54F",
          error: "#EF5350",
          "--rounded-box": "0.75rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
      },
    ],
  },
};
